export enum RESIZE_DIRECTIONS {
  TOP,
  BOTTOM,
  LEFT,
  RIGHT,
  TOPLEFT,
  TOPRIGHT,
  BOTTOMLEFT,
  BOTTOMRIGHT,
}

export enum TAB_TRANSLATE_STATUS {
  DEFAULT = "DEFAULT",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
}

export enum TAB_MOVE_STATUS {
  DEFAULT = "DEFAULT",
  DIVIDED = "DIVIDED",
  COMBINE = "COMBINE",
}

export enum CUSTOM_ZINDEX {
  DEFAULT = "initial",
  FOREGROUND = "10",
  OVERLAY = "20",
}
